---
abstract: 'Main backend module'
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RackMan
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::Diff: 0
  Carp: 0
  Config::IniFiles: 0
  Cwd: 0
  DBD::mysql: 0
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  Exporter: 0
  File::Basename: 0
  File::Path: 0
  File::Temp: 0
  Getopt::Long: 0
  HTML::Template: 2.0
  HTML::Template::Filter::TT2: 0.03
  IPC::Run: 0
  JSON: 0
  List::MoreUtils: 0
  Moose: 1.00
  MooseX::NonMoose: 0
  Net::FTP: 0
  Net::ILO: 0.54
  Net::SNMP: 0
  Net::Telnet::Cisco: 0
  NetAddr::IP: 4.000
  Path::Class: 0
  Socket: 0
  Term::ANSIColor: 0
  Test::More: 0.45
  YAML: 0
  namespace::autoclean: 0
version: 1.14
